name: Gettext Updates
on:
  push:
    branches: main
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: PlayNux/actions/gettext-template@main
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "Playnux-bot"
        GIT_USER_EMAIL: "brokenlens98@gmail.com"
